---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
        args:
          - "--skip-string-normalization"

  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.31.0"
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
        additional_dependencies:
          - types-requests
          - types-pyyaml

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=100"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--profile"
          - "black"
          - "--filter-files"

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args:
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
